"""empty message

Revision ID: 081bd1539c1c
Revises: 582e1482d60c
Create Date: 2023-11-07 20:28:33.726741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081bd1539c1c'
down_revision = '582e1482d60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_constraint('log_car_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_unique_constraint('log_car_id_key', ['car_id'])

    # ### end Alembic commands ###
