"""empty message

Revision ID: 3e50ac5b010c
Revises: 
Create Date: 2023-11-07 16:47:41.312445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e50ac5b010c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.String(length=150), nullable=False),
    sa.Column('displayName', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('miles', sa.String(length=10), nullable=True),
    sa.Column('cost', sa.String(length=10), nullable=True),
    sa.Column('mechanic', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('car_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.uid'], ),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('car')
    op.drop_table('user')
    # ### end Alembic commands ###
