"""empty message

Revision ID: 582e1482d60c
Revises: bdef7c1ea040
Create Date: 2023-11-07 17:37:45.237523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582e1482d60c'
down_revision = 'bdef7c1ea040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_constraint('car_uid_fkey', type_='foreignkey')
        batch_op.drop_column('uid')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_constraint('log_uid_fkey', type_='foreignkey')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('log_uid_fkey', 'user', ['uid'], ['uid'])

    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('car_uid_fkey', 'user', ['uid'], ['uid'])

    # ### end Alembic commands ###
